#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Analyze settled crypto 15m paper trades and decide whether the model is usable.

Reads paper_logs/crypto_15m_settled_v2.csv generated by crypto_15m_settlement.py.
Produces grouped diagnostics by asset/action/elapsed/edge buckets and a hard
NO-GO / PAPER-ONLY / CANDIDATE verdict.

No wallet, no signing, no orders.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


def fnum(x, default=0.0) -> float:
    try:
        if x in (None, "", "nan", "NaN"):
            return default
        return float(x)
    except Exception:
        return default


def inum(x, default=0) -> int:
    try:
        if x in (None, ""):
            return default
        return int(float(x))
    except Exception:
        return default


def bval(x) -> bool:
    return str(x).strip().lower() in {"true", "1", "yes", "y"}


def read_csv(path: Path) -> List[dict]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def bucket_edge(edge: float) -> str:
    if edge < 0.08:
        return "edge_006_008"
    if edge < 0.12:
        return "edge_008_012"
    if edge < 0.18:
        return "edge_012_018"
    return "edge_ge_018"


def bucket_elapsed(sec: int) -> str:
    if sec < 180:
        return "elapsed_060_180"
    if sec < 360:
        return "elapsed_180_360"
    if sec < 540:
        return "elapsed_360_540"
    return "elapsed_ge_540"


def bucket_prob(prob: float) -> str:
    if prob < 0.55:
        return "prob_lt_055"
    if prob < 0.65:
        return "prob_055_065"
    if prob < 0.75:
        return "prob_065_075"
    return "prob_ge_075"


def summarize(rows: List[dict]) -> dict:
    n = len(rows)
    if n == 0:
        return {"n": 0, "wins": 0, "wr": 0.0, "pnl": 0.0, "avg": 0.0, "avg_edge": 0.0, "max_dd": 0.0}
    wins = sum(1 for r in rows if bval(r.get("win")))
    pnl = sum(fnum(r.get("pnl_usd")) for r in rows)
    avg_edge = sum(fnum(r.get("edge")) for r in rows) / n
    eq = 0.0
    peak = 0.0
    dd = 0.0
    for r in sorted(rows, key=lambda x: inum(x.get("ts_ms"))):
        eq += fnum(r.get("pnl_usd"))
        peak = max(peak, eq)
        dd = min(dd, eq - peak)
    return {"n": n, "wins": wins, "wr": wins / n, "pnl": pnl, "avg": pnl / n, "avg_edge": avg_edge, "max_dd": dd}


def dedupe_first(rows: List[dict]) -> List[dict]:
    out: Dict[Tuple[str, int, str], dict] = {}
    for r in sorted(rows, key=lambda x: inum(x.get("ts_ms"))):
        key = (str(r.get("asset")), inum(r.get("market_window_ts")), str(r.get("action")))
        if key not in out:
            out[key] = r
    return list(out.values())


def group_by(rows: List[dict], key_fn) -> Dict[str, List[dict]]:
    g: Dict[str, List[dict]] = defaultdict(list)
    for r in rows:
        g[key_fn(r)].append(r)
    return g


def print_group(label: str, groups: Dict[str, List[dict]], min_n: int = 1) -> None:
    print(f"=== {label} ===")
    summaries = []
    for k, rs in groups.items():
        s = summarize(rs)
        if s["n"] >= min_n:
            summaries.append((k, s))
    summaries.sort(key=lambda kv: (kv[1]["pnl"], kv[1]["wr"], kv[1]["n"]), reverse=True)
    for k, s in summaries:
        print(
            f"CRYPTO15_DIAG_GROUP group={label}:{k} trades={s['n']} wins={s['wins']} "
            f"wr={s['wr']:.4f} pnl={s['pnl']:.4f} avg={s['avg']:.4f} "
            f"avg_edge={s['avg_edge']:.4f} max_dd={s['max_dd']:.4f}"
        )


def verdict(s: dict, assets_positive: int) -> Tuple[str, str]:
    if s["n"] < 100:
        return "NO_LIVE", "sample_too_small"
    if s["pnl"] <= 0:
        return "NO_LIVE", "negative_pnl"
    if s["wr"] < 0.55:
        return "NO_LIVE", "win_rate_below_55"
    if s["max_dd"] < -15.0:
        return "NO_LIVE", "drawdown_too_high"
    if assets_positive < 2:
        return "NO_LIVE", "less_than_two_assets_positive"
    return "PAPER_CANDIDATE", "passed_minimum_paper_gate"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--settled", default="paper_logs/crypto_15m_settled_v2.csv")
    p.add_argument("--min-group-n", type=int, default=3)
    args = p.parse_args()

    rows_all = read_csv(Path(args.settled))
    rows = dedupe_first(rows_all)
    s_all = summarize(rows_all)
    s = summarize(rows)
    asset_groups = group_by(rows, lambda r: str(r.get("asset")))
    asset_pos = sum(1 for _, rs in asset_groups.items() if summarize(rs)["pnl"] > 0)
    status, reason = verdict(s, asset_pos)

    print(
        f"CRYPTO15_ANALYZER_SUMMARY status={status} reason={reason} "
        f"raw={len(rows_all)} first_dedup={len(rows)} "
        f"all_wr={s_all['wr']:.4f} all_pnl={s_all['pnl']:.4f} all_avg={s_all['avg']:.4f} "
        f"first_wr={s['wr']:.4f} first_pnl={s['pnl']:.4f} first_avg={s['avg']:.4f} "
        f"first_max_dd={s['max_dd']:.4f} avg_edge={s['avg_edge']:.4f} assets_positive={asset_pos}"
    )

    print_group("asset", asset_groups, min_n=1)
    print_group("asset_action", group_by(rows, lambda r: f"{r.get('asset')}:{r.get('action')}"), min_n=1)
    print_group("elapsed_bucket", group_by(rows, lambda r: bucket_elapsed(inum(r.get("elapsed_sec")))), min_n=args.min_group_n)
    print_group("edge_bucket", group_by(rows, lambda r: bucket_edge(fnum(r.get("edge")))), min_n=args.min_group_n)
    print_group("prob_bucket", group_by(rows, lambda r: bucket_prob(fnum(r.get("model_prob")))), min_n=args.min_group_n)
    print_group("asset_elapsed", group_by(rows, lambda r: f"{r.get('asset')}:{bucket_elapsed(inum(r.get('elapsed_sec')))}"), min_n=args.min_group_n)

    # Candidate rule hints: only report groups with at least min-group-n and positive PnL.
    print("=== candidate_rule_hints ===")
    candidates = []
    for label, groups in [
        ("asset", asset_groups),
        ("asset_action", group_by(rows, lambda r: f"{r.get('asset')}:{r.get('action')}")),
        ("elapsed_bucket", group_by(rows, lambda r: bucket_elapsed(inum(r.get("elapsed_sec"))))),
        ("edge_bucket", group_by(rows, lambda r: bucket_edge(fnum(r.get("edge"))))),
        ("asset_elapsed", group_by(rows, lambda r: f"{r.get('asset')}:{bucket_elapsed(inum(r.get('elapsed_sec')))}")),
    ]:
        for k, rs in groups.items():
            ss = summarize(rs)
            if ss["n"] >= args.min_group_n and ss["pnl"] > 0:
                candidates.append((label, k, ss))
    candidates.sort(key=lambda x: (x[2]["pnl"], x[2]["wr"], x[2]["n"]), reverse=True)
    if not candidates:
        print("CRYPTO15_RULE_HINT none reason=no_positive_group_with_min_sample")
    else:
        for label, k, ss in candidates[:20]:
            print(
                f"CRYPTO15_RULE_HINT label={label} key={k} trades={ss['n']} wr={ss['wr']:.4f} "
                f"pnl={ss['pnl']:.4f} avg={ss['avg']:.4f} avg_edge={ss['avg_edge']:.4f}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
